version: '3.5'

services:

  bahmni:
    image: localhost:5000/${image_name}:${image_version}
    hostname: ${bahmni_implementation_name}-emr-${mode}
    container_name: ${bahmni_implementation_name}-emr-${mode}-container
    tmpfs: /tmp
    environment:
      - BAHMNI_IMPL_NAME=${bahmni_implementation_name}
      - BAHMNI_SERVER_MODE=$mode
      - BAHMNI_SETUP_REPLICATION=$setup_replication
      - BAHMNI_OPENELIS_ENABLED=$bahmni_openelis_enabled
      - BAHMNI_REPORTS_ENABLED=$bahmni_reports_enabled
      - BAHMNI_REPLICATION_USERNAME=$bahmni_replication_username
      - BAHMNI_REPLICATION_PASSWORD=$bahmni_replication_password
      - BAHMNI_ACTIVE_HOST=$bahmni_active_host
      - BAHMNI_PASSIVE_HOST=$bahmni_passive_host
      - BAHMNI_ENC_FILE_PATH=$bahmni_enc_file_path
      - BAHMNI_BACKUP_PASSIVE=$bahmni_backup_passive
      - BAHMNI_BACKUP_NESTOR=$bahmni_backup_nestor
      - BAHMNI_NESTOR_HOST=$nestor_host
      - BAHMNI_NESTOR_RSYNC_PATH=$bahmni_nestor_rsync_path
      - BAHMNI_NESTOR_BACKUP_DIR=$nestor_backup_dir
    command: ["/start.sh", "${mode}", "${setup_replication}"]
    restart: always
    volumes:
      - type: volume
        source: bahmni_bahmni_backup
        target: /bahmni_backup/backups
      - type: volume
        source: bahmni_mysql_data
        target: /var/lib/mysql
      - type: volume
        source: bahmni_pgsql_data
        target: /var/lib/pgsql
      - type: volume
        source: bahmni_bahmni_home
        target: /home/bahmni
      - type: bind
        source: ${bahmni_enc_host_path}
        target: ${bahmni_enc_file_path}
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

volumes:
  bahmni_bahmni_backup:
  bahmni_mysql_data:
  bahmni_pgsql_data:
  bahmni_bahmni_home:

