version: '3.3'

services:

  chk:
    image: localhost:5000/chk:0.1
    hostname: ${hostname}
    container_name: ${hostname}-container
    tmpfs: /tmp
    environment:
      - BAHMNI_SERVER_MODE=$mode
      - BAHMNI_SETUP_REPLICATION=$setup_replication
      - BAHMNI_ACTIVE_HOST=$bahmni_active_host
      - BAHMNI_PASSIVE_HOST=$bahmni_passive_host
      - BAHMNI_ENC_FILE_PATH=$bahmni_enc_file_path
      - BAHMNI_BACKUP_PASSIVE=$bahmni_backup_passive
      - BAHMNI_BACKUP_NESTOR=$bahmni_backup_nestor
      - BAHMNI_NESTOR_BACKUP_DIR=$nestor_backup_dir
    command: "bash -e /start.sh ${mode} ${setup_replication}"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"   # SSH for syncing backups
      - "3306:3306" # Mysql replication
      - "5432:5432" # PostgreSQL replication
      - "8050:8050" # OpenMRS atomfeed
      - "8052:8052" # OpenELIS atomfeed

    volumes:
      - type: volume
        source: chk_bahmni_backup
        target: /bahmni_backup/backups
      - type: volume
        source: chk_mysql_data
        target: /var/lib/mysql
      - type: volume
        source: chk_pgsql_data
        target: /var/lib/pgsql
      - type: volume
        source: chk_openmrs_lucene
        target: /opt/openmrs/lucene
      - type: volume
        source: chk_bahmni_home
        target: /home/bahmni
      - type: bind
        source: ${bahmni_enc_file_path}
        target: ${bahmni_enc_file_path}

volumes:
  chk_bahmni_backup:
  chk_mysql_data:
  chk_pgsql_data:
  chk_openmrs_lucene:
  chk_bahmni_home:

