version: '3.3'

services:

  bahmni:
    build:
      context: bahmni
      dockerfile: Dockerfile
      args:
        - BAHMNI_IMPL_FILE_SUFFIX=${impl_file_suffix}
        - BAHMNI_INSTALLER_URL=${bahmni_installer_url}
        - BAHMNI_IMPLEMENTATION_REPO=${bahmni_implementation_repo}
        - BAHMNI_IMPLEMENTATION_BRANCH=${bahmni_implementation_branch}
        - BAHMNI_POSTGRES_PRESENT=$bahmni_postgres_present

