version: "3.5"

services:

  bahmni-uat:
    image: localhost:5000/${image_name}:${image_version_uat}
    hostname: ${bahmni_implementation_name}-emr-uat
    container_name: ${bahmni_implementation_name}-emr-uat-container
    tmpfs: /tmp
    environment:
      - BAHMNI_IMPL_NAME=${bahmni_implementation_name}
      - BAHMNI_SERVER_MODE=active
      - BAHMNI_SETUP_REPLICATION=no
      - BAHMNI_OPENELIS_ENABLED=$bahmni_openelis_enabled
      - BAHMNI_REPORTS_ENABLED=$bahmni_reports_enabled
      - BAHMNI_REPLICATION_USERNAME=$bahmni_replication_username
      - BAHMNI_REPLICATION_PASSWORD=$bahmni_replication_password
      - BAHMNI_ACTIVE_HOST=localhost
      - BAHMNI_PASSIVE_HOST=
      - BAHMNI_ENC_FILE_PATH=$bahmni_enc_file_path
      - BAHMNI_SKIP_BACKUPS=yes
      - BAHMNI_BACKUP_PASSIVE=no
      - BAHMNI_BACKUP_NESTOR=no
      - BAHMNI_NESTOR_BACKUP_DIR=$nestor_backup_dir
    command: ["/start.sh", "active", "no"]
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emr-uat-${INSTANCE_NAME:-}.entrypoints=websecure"
      - "traefik.http.routers.emr-uat-${INSTANCE_NAME:-}.rule=Host(`${EMR_HOST_NAME:-local-test.emr.ocb.msf.org}`)"
      - "traefik.http.routers.emr-uat-${INSTANCE_NAME:-}.tls.certresolver=letsencrypt_dns"
    expose:
      - 80
    volumes:
      - type: volume
        source: bahmni_uat_mysql_data
        target: /var/lib/mysql
      - type: volume
        source: bahmni_uat_pgsql_data
        target: /var/lib/pgsql
      - type: bind
        source: ${bahmni_enc_host_path}
        target: ${bahmni_enc_file_path}
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - default
      - web

volumes:
  bahmni_uat_mysql_data:
  bahmni_uat_pgsql_data:

networks:
  web:
    external: yes

