version: '3.3'

services:

  bahmni:
    build:
      context: bahmni
      dockerfile: Dockerfile
      args:
        - impl_file_suffix=${impl_file_suffix}
        - bahmni_installer_url=${bahmni_installer_url}
        - bahmni_implementation_repo=${bahmni_implementation_repo}
        - bahmni_implementation_branch=${bahmni_implementation_branch}

